#!/usr/bin/env python3
"""Regenerate docs/README.md from per-file `**Doc status:**` headers.

Every file in docs/design/ carries, within its first five lines,
    **Doc status:** <tier> · <one-line hook>
with <tier> one of: living | reference | survey | historical | superseded by <file>.
This script groups the docs by tier and rewrites docs/README.md's index. Run it
whenever a design doc is added, retired, or changes tier (the session wrap-up
checklist in CLAUDE.md names the triggers). Exits non-zero if a file lacks a header.

    uv run python scripts/docs_index.py            # rewrite docs/README.md
    uv run python scripts/docs_index.py --check    # verify only (CI / pre-commit)
"""
from __future__ import annotations

import glob
import os
import re
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESIGN = os.path.join(ROOT, 'docs', 'design')
README = os.path.join(ROOT, 'docs', 'README.md')
DECISIONS = os.path.join(ROOT, 'docs', 'decisions')
STATUS_RE = re.compile(r'^\*\*Doc status:\*\*\s*(living|reference|survey|historical|superseded by \S+)\s*·\s*(.+?)\s*$')
TIERS = [
    ('living', 'Living (updated as work lands)'),
    ('reference', 'Reference (stable, still load-bearing)'),
    ('survey', 'Surveys (ecosystem intelligence, dated snapshots)'),
    ('historical', 'Historical (closed-milestone plans, adopted drafts, forensics — kept for provenance; the closeout ADRs supersede them)'),
    ('superseded', 'Superseded (pointer kept for link stability)'),
]


def scan() -> tuple[dict[str, list[tuple[str, str, str]]], list[str]]:
    groups: dict[str, list[tuple[str, str, str]]] = {k: [] for k, _ in TIERS}
    missing: list[str] = []
    for path in sorted(glob.glob(os.path.join(DESIGN, '*.md'))):
        name = os.path.basename(path)
        with open(path, encoding='utf-8') as fh:
            head = [next(fh, '') for _ in range(5)]
        title = head[0].lstrip('# ').strip() if head and head[0].startswith('# ') else name
        m = next((STATUS_RE.match(l.rstrip('\n')) for l in head if STATUS_RE.match(l.rstrip('\n'))), None)
        if not m:
            missing.append(name)
            continue
        tier, hook = m.group(1), m.group(2)
        key = 'superseded' if tier.startswith('superseded') else tier
        hook = hook if key != 'superseded' else f'{tier} — {hook}'
        groups[key].append((name, title, hook))
    return groups, missing


def render(groups: dict[str, list[tuple[str, str, str]]]) -> str:
    adrs = sorted(f for f in os.listdir(DECISIONS) if f.startswith('ADR-'))
    last_adr = adrs[-1][4:8] if adrs else '0000'
    open_plans = [n for n, _, _ in groups['living'] if re.match(r'm\d+-plan\.md$', n)]
    open_plan = open_plans[0] if open_plans else 'design/anvil-design-v2.md'
    out = [
        '# docs/ — index and reading order',
        '',
        f'*Generated by `scripts/docs_index.py` from each design doc\'s `**Doc status:**` line '
        f'(last run {date.today().isoformat()}). Edit the status lines, not this file. Files never move '
        'out of their directories — everything here is a link target from CLAUDE.md, ADRs, and the '
        'project map — so this index is the navigation layer.*',
        '',
        '## Start here',
        '',
        '1. [CLAUDE.md](../CLAUDE.md) — the constitution: invariants, conventions, the live Status (Now / state of record / milestone table) and the session wrap-up checklist.',
        '2. [design/anvil-design-v2.md](design/anvil-design-v2.md) — **the canonical design doc.** Why and what; section numbers (§1–§15) are referenced everywhere.',
        f'3. [design/{open_plan}](design/{open_plan}) — the open milestone plan, with its running record.',
        '4. [standing-rules.md](standing-rules.md) — every measured rule the milestones have birthed, one line each with its ADR. Read the relevant section before designing any run, gate, instrument, or curation cycle.',
        '5. [project-map.html](project-map.html) — the dashboard: Now panel, state-of-record table, run ledger, ADR index.',
        '6. [forge-ai-field-guide.md](forge-ai-field-guide.md) — the traps we measured, with detection and fix. Written for other Forge-AI builders.',
        '7. [status-archive.md](status-archive.md) — every CLAUDE.md Status bullet verbatim at the moment it was archived (closed milestones, track snapshots).',
        '',
        '## Directories',
        '',
        f'- **`decisions/`** — ADRs, numbered sequentially (0001–{last_adr} so far; `TEMPLATE.md` at the root). Authoritative for every resolved design question. The project map carries a one-line-per-ADR index. Numbering hazard: parallel sessions collide — `ls` for max+1 at write time.',
        '- **`design/`** — design docs, plans, specs, drafts and surveys (breakdown below, grouped by the status line each file carries).',
        '- **`devlog/`** — one dated file per working session (`YYYY-MM-DD[-sessionN].md`, from `TEMPLATE.md`). The session-by-session narrative; nothing else duplicates it.',
        '',
        '## design/ breakdown',
        '',
    ]
    for key, heading in TIERS:
        items = groups[key]
        if not items:
            continue
        out.append(f'**{heading}:**')
        out.append('')
        for name, title, hook in items:
            out.append(f'- [{name}](design/{name}) — {hook}')
        out.append('')
    return '\n'.join(out).rstrip('\n') + '\n'


def main(argv: list[str]) -> int:
    groups, missing = scan()
    if missing:
        print('design docs without a **Doc status:** line:', *missing, sep='\n  ', file=sys.stderr)
        return 1
    text = render(groups)
    if '--check' in argv:
        current = open(README, encoding='utf-8').read() if os.path.exists(README) else ''
        strip = lambda s: re.sub(r'\(last run \d{4}-\d{2}-\d{2}\)', '', s)
        if strip(current) != strip(text):
            print('docs/README.md is stale — run scripts/docs_index.py', file=sys.stderr)
            return 1
        print('docs/README.md up to date')
        return 0
    with open(README, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print(f'wrote {README}: ' + ', '.join(f'{k} {len(v)}' for k, v in groups.items() if v))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
